easy_admin:
  site_name: 'Easy Budget'
  entities:
    Client:
      class: App\Entity\Client
      label: 'Clients'
      list:
        title: "List of clients"
    Invoice:
      class: App\Entity\Invoice
      label: 'Invoices'
      list:
        title: "Last invoices"

