version: '3.5'

# Configure a secondary network for traefik
# - "default"
# - "trafik" which is an external network, define to root connection from traefik reverse proxy
#
networks:
  traefik:
    external:
      name: ${TRAEFIK_NETWORK:-traefik_proxy}

# Define services
#
services:
  web:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/project/
    depends_on:
      - fpm
    labels:
      traefik.port: "80"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${HOSTNAME:-budget.local}"
      traefik.docker.network: "${TRAEFIK_NETWORK:-traefik_proxy}"
      traefik.frontend.priority: "1"
    networks:
      default:
        aliases:
          - test.budget.local
      traefik:

  fpm:
    build:
      context: ./docker/fpm
    volumes:
      - ./:/var/www/project/
    working_dir: /var/www/project/
    environment:
      DATABASE_URL: "pgsql://user:passwd@postgres:5432/budget"
    depends_on:
      - postgres
    networks:
      default:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: budget
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      default:
      traefik:

  selenium:
    build:
      context: docker/selenium
      shm_size: 2gb
    depends_on:
      - web
    networks:
      default:

  codeception:
    build:
      context: ./docker/codeception
    environment:
      SELENIUM_HOST: "selenium:4444"
      COMPOSER_AUTH: ${COMPOSER_AUTH:-""}
      POSTGRES_HOST: postgres
      POSTGRES_DB: budget
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./:/var/www/project/
    working_dir: /var/www/project/
    depends_on:
      - web
      - selenium
#    command: ./vendor/bin/codecept run --coverage
    networks:
      default:
