# .circleci/config.yml
version: 2.1

# Require orbs
orbs:
  codecov: codecov/codecov@1.0.4

# Define reusable executors
executors:
  # PHP 7.3 Cli Alpine executor
  php73cli-alpine:
    docker:
      - image: jeckel/php-test:7.3-cli-alpine
    working_directory: /home/circleci/project

  # Docker-compose executor
  docker-compose:
    machine:
      docker_layer_caching: true
    working_directory: /home/circleci/project

# Configure Jobs:
jobs:
  composer:
    executor: php73cli-alpine
    steps:
      - checkout

      - restore_cache:
          name: Restore composer's vendor cache
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install composer deps
          command: composer install --no-suggest --no-interaction
      - save_cache:
          name: Save composer's vendor in cache
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - "vendor"
      - persist_to_workspace:
          root: /home/circleci
          paths: project

  codeception:
    executor: docker-compose
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Pull and build images
          command: |
            docker-compose pull
            docker-compose build
      - run:
          name: Launch services
          command: |
            if [ `docker network ls | grep -c -w traefik_proxy` -eq 0 ]; then
                docker network create traefik_proxy
            fi
            docker-compose up -d web fpm selenium
      - run:
          name: Run codeception
          command: docker-compose run --rm codeception wait-for-it.sh selenium:4444 -- ./vendor/bin/codecept run --coverage --coverage-html --coverage-xml

      - codecov/upload:
          file: tests/_output/coverage.xml

      - store_artifacts:
          path: tests/_output

  phpstan:
    executor: php73cli-alpine
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: PHP Stan
          command: vendor/bin/phpstan analyse

  phpcs:
    executor: php73cli-alpine
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: PHP Code Sniffer
          command: vendor/bin/phpcs

  phpmd:
    executor: php73cli-alpine
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: PHP Mess Detector
          command: vendor/bin/phpmd src text cleancode,codesize,design,naming,unusedcode

  builds_completed:
    docker:
      - image: docker:git
    steps:
      - run: echo "Builds completed with success"

# Define the workflow:
workflows:
  version: 2
  build:
    jobs:
      - composer
      - codeception:
          requires:
            - composer
      - phpstan:
          requires:
            - composer
      - phpcs:
          requires:
            - composer
      - phpmd:
          requires:
            - composer
      - builds_completed:
          requires:
            - codeception
            - phpstan
            - phpcs
            - phpmd
